title: dtc innovation
tag_text: dtc innovation
description: Designing Technology for the Commons.
baseurl: ""
url: https://dtc-innovation.org

permalink: /writings/:year/:title

default_locale: en
locales:
  en: English
  fr: Français

collections:
  projects_en:
    output: true
    permalink: /en/projects/:title
    resources:
      github: GitHub Project
      website: Website
  projects_fr:
    output: true
    permalink: /fr/projets/:title
    resources:
      github: Projet GitHub
      website: Site web
  assemblies:
    output: true
    permalink: /dna/assemblies/:slug.html


company:
  siren: '823553557'
  siret: '82355355700013'
  vat: 'FR67823553557'
  rna: 'W332020707'
  ape: '6201Z'
  since: 2016-10-05

defaults:
  - scope:
      path: "fr"
    values:
      lang: "fr"
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      type: "posts"
    values:
      layout: "writing"
  - scope:
      type: "projects_en"
    values:
      layout: "project"
  - scope:
      type: "projects_fr"
    values:
      layout: "project"
  - scope:
      type: "assemblies"
    values:
      layout: "page"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
